<div class="quiz">
	<div class="quizBloc">
		<label for="title" class="quizConteneurLabel"></label>
		<div class="quizConteneur">
			<?php echo $this->element->title ?>
		</div>
		<div style="clear:both;"> </div>
	</div>
	
	<div class="quizBloc">
		<label for="descr" class="quizConteneurLabel"></label>
		<div class="quizConteneur">
			<?php echo $this->element->descr ?>
		</div>
		<div style="clear:both;"> </div>
	</div>	
	
	<div class="quizBloc">
		<label for="level" class="quizConteneurLabel"></label>
		<div class="quizConteneur">
			<?php echo $this->element->level ?>
		</div>
		<div style="clear:both;"> </div>
	</div>
	
	<div class="quizBloc">
		<label for="nbQuestion" class="quizConteneurLabel"></label>
		<div class="quizConteneur">
			<?php echo $this->element->nbQuestion ?>
		</div>
		<div style="clear:both;"> </div>
	</div>
	
	<div class="quizBloc">
		<label for="duration" class="quizConteneurLabel"></label>
		<div class="quizConteneur">
			<?php echo $this->element->duration ?>
		</div>
		<div style="clear:both;"> </div>
	</div>
	
	<div class="quizBloc">
		<label for="theme" class="quizConteneurLabel"></label>
		<div class="quizConteneur">
			<?php echo $this->element->theme ?>
		</div>
		<div style="clear:both;"> </div>
	</div>
	
	<div class="quizBlocButton">
		<div class="quizConteneur">
			<?php echo $this->element->Enregistrer ?>
		</div>
	</div>
</div>