<h1><?php echo 'QUIZZ !!!'; ?></h1>

<div class="btn"><a href="/quiz/new">Créer un Quizz</a></div>
<br /><br />
<div>
	<table class="zebra-striped">
		<tr>
			<th colspan="7">
				Liste des Quizz
			</th>
		</tr>
		<tr>
			<th>
				Titre
			</th>
			<th width="150">
				Description
			</th>
			<th>
				Nombre de question
			</th>
			<th>
				Durée
			</th>
			<th>
				Difficulté
			</th>
			<th>
				Modifier
			</th>
			<th>
				Supprimer
			</th>
		</tr>
	<?php
	foreach ($this->quizList as $quiz)
	{
	?>
		<tr>
			<td>
				<?php
					echo $quiz->getQuizTitle();
				?>
			</td>
			<td>
				<?php
					echo $quiz->getDescr();
				?>
			</td>
			<td>
				<?php
					echo $quiz->getNbrQuestion();
				?>
			</td>
			<td>
				<?php
					echo $quiz->getDuration();
				?>
			</td>
			<td>
				<?php
					$level = $this->levelMapper->find($quiz->getLevel());
					echo $level->getLevel();
				?>
			</td>
			<td>
				<div class="btn"><a href="<?php echo $this->url(array('quizId'=>$quiz->getQuizId()), 'quizEdit')?>">Modifier le Quizz</a></div>
			</td>
			<td>
				<a class="close" href="<?php echo $this->url(array('quizId'=>$quiz->getQuizId()), 'quizDel')?>">×</a>
			</td>			
		</tr>
	<?php
	}
	?>
	</table>
</div>