<?php echo $this->doctype()?>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <?php 
	$this->headMeta()->setCharset('UTF-8');
	echo $this->headMeta() . PHP_EOL;
  ?>

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
	   More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <?php 
	$this->headTitle(
		$this->translate('title_main')
	);
	echo $this->headTitle()
			  ->setSeparator(' - ')
  ?> 
  <meta name="description" content="">
  <meta name="keywords" content="">
  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <?php 
   $this->headLink()->appendStylesheet('/css/style.css');
   $this->headLink()->appendStylesheet('/css/bootstrap.css');
   $this->headLink()->appendStylesheet('/css/docs.css');
   
   echo $this->headLink();
  ?>

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
	   Modernizr enables HTML5 elements & feature detects for optimal performance.
	   Create your own custom Modernizr build: www.modernizr.com/download/ -->
  <?php 
	$this->headScript()->appendFile('/js/libs/modernizr-2.5.3.min.js');
	echo $this->headScript();
  ?>   
</head>
<body>
 <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
	   chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  <header>
		<h1>Projet www5</h1>
  </header>
  <div role="main" style="height:100%;">
	<div class="topbar" data-scrollspy="scrollspy">
	  <div class="topbar-inner">
		<a class="brand" href=""><img src='../css/img/logo.png' /></a>
		<div class="container canvas">
		  <?php 
		  
		  ?>
		</div>
	  </div>
  </div>
	<div class="container canvas">
   <div class="content-canvas">
	   <div class="breadcrumb">
	   <?php echo $this->translate('breadcrumbs_begining')?> :
	   <?php 
		  echo $this->navigation()
					->breadcrumbs()
					->setMinDepth(0);
	   ?>
	   </div>
	   
	   <?php echo $this->layout()->content ?>
   </div>
   <footer>
		<p>&copy; Company 2011</p>
	</footer>


  <!-- JavaScript at the bottom for fast page loading -->

<?php 
	$this->inlineScript()->prependFile('/js/login.js');
	$this->inlineScript()->prependFile('/js/jquery.counter.min.js');
	$this->inlineScript()->prependFile('/js/jquery.autosize.min.js');
	$this->inlineScript()->prependFile('/js/bootstrap-dropdown.js');
	$this->inlineScript()->prependFile('/js/bootstrap-alerts.js');
	$this->inlineScript()->prependFile('/js/libs/jquery-1.7.1.min.js');

	echo $this->inlineScript();
  ?>   
</body>
</html>
	
	
	
	