<div id="liste-quiz">
	<label class="titre">SELECTIONNEZ VOTRE QUIZ</label>
	<div class="ctnr-quiz">
		<label class="titre-quiz">QUIZ N°1 : Test 1</label>
		<div class="dificulty-blue"></div>
	</div>
	<div class="description">
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis diam metus, euismod vitae accumsan eu, ornare eu nisi. Mauris mauris augue, interdum ac vehicula eget, placerat varius leo. Cras egestas pretium mattis. Aliquam erat volutpat. Cum sociis natoqu
	</div>
	<div class="ctnr-quiz">
		<label class="titre-quiz">QUIZ N°2 : Test 1</label>
		<div class="dificulty-blue"></div>
	</div>
	<div class="ctnr-quiz">
		<label class="titre-quiz">QUIZ N°3 : Test 1</label>
		<div class="dificulty-green"></div>
	</div>
	<div class="ctnr-quiz">
		<label class="titre-quiz">QUIZ N°4 : Test 1</label>
		<div class="dificulty-red"></div>
	</div>
	<div class="ctnr-quiz">
		<label class="titre-quiz">QUIZ N°5 : Test 1</label>
		<div class="dificulty-red"></div>
	</div>
</div>