<?php
 // echo "OUAI TROP BIEN CA MARCHE ... OU PAS";
// if($this->isConnect !== true ):
?>
<div class="dialog">
	<label>BIENVENUE</label>
	<div>
		<p class="text-accueil">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque ligula id libero porttitor sed semper turpis pulvinar. Aenean velit eros, volutpat in egestas et, accumsan at magna. Nulla facilisi. Ut tempus, nunc vel faucibus laoreet, arcu leo pellentesque metus, id dictum dolor dolor eu urna. Nunc ornare, mi ut viverra viverra, enim neque auctor ipsum, ac euismod turpis leo in nulla. Sed adipiscing cursus neque, vel faucibus justo convallis ut. Proin sagittis molestie consequat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin id purus nisl, in sodales felis. Aenean sit amet dui lectus. Morbi accumsan, erat non euismod rutrum, lectus turpis semper eros, quis mattis ipsum ligula in nisl. Vestibulum lacus justo, varius varius fringilla dignissim, tincidunt aliquet mi. In hac habitasse platea dictumst. Sed ac ligula vel urna tristique varius vitae a ante.</p>

		<div class="dialog-ctr-button">
			<div class="dialog-button-left"></div>
			<button class="dialog-button" value="Login" ><label class="button-value">Login</label></button>
			<div class="dialog-button-right" style="margin-right: 30px;"></div>
		</div>
		<div class="dialog-ctr-button">
			<div class="dialog-button-left"></div>
			<button class="dialog-button" value="inscription" ><label class="button-value">Inscription</label></button>
			<div class="dialog-button-right"></div>
		</div>
	</div>
</div>
